---
- hosts: servers
  become: yes
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
  vars:
    sysctl_overwrite:
    # also needed for docker
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
