- hosts: servers
  become: yes
  gather_facts: yes
  vars:
    wireguard_port: 51820
    client_name: 'client1'
    subnet: '10.0.0'
    dns_server: "1.1.1.3"
  tasks:
    # ...
    - name: Install qrencode
      apt:
        name: qrencode
        state: present
      when: ansible_os_family == "Debian"

    - name: Generate QR code for the client configuration
      shell: qrencode -t ansiutf8 < /etc/wireguard/{{ client_name }}.conf
      register: qr_code
      changed_when: false
      run_once: true

    - name: Display QR code
      debug:
        msg: "{{ qr_code.stdout_lines }}"
      run_once: true

