- hosts: servers
  become: yes
  gather_facts: no
  tasks:
    - name: Find all client configuration files
      find:
        paths: "/etc/wireguard/"
        patterns: "*.conf"
        excludes: "wg0.conf"
      register: found_files

    - name: Simplify output to just file paths
      set_fact:
        file_paths: "{{ found_files.files | map(attribute='path') | list }}"
      
    - name: Display client configuration files
      debug:
        var: file_paths
