---
- hosts: servers
  become: yes
  vars:
    wireguard_address: '10.99.0.1/24'
    wireguard_port: 51820
    dns_server: '10.99.0.1'
  tasks:
    - name: Check WireGuard server status
      command: wg show wg0
      register: wireguard_status
      ignore_errors: true

    - name: Display WireGuard server status
      debug:
        var: wireguard_status.stdout_lines
        